### ISSUE TITLE
how to deploy it?

### ISSUE THREAD

**Issue by shenfumin** [megagao/IndoorPos#1]
could you share me some document about how to deploy it on server?

**Comment by megagao** [comment]
Plz give me your email address, and i will send u the sql file.

**Comment by shenfumin** [comment]
thanks your response. my email is shenfumin@163.com.

**Comment by jingyuzhu** [comment]
i need the sql file also , my email is  513029899@qq.com
thx!

**Comment by ElanII** [comment]
Please can explain also to me with some instruction if possibile? carlo.oldani@me.com
thanks a lot in advance

**Comment by yujiaao** [comment]
Please send me the sql file to yujiaao@msn.com, Thank you!

**Comment by stepcar** [comment]
please send me the sql file,my email address is stepcar@sina.com

**Comment by Tonny726** [comment]
Hi,I need the sql file also , my email is 568796595@qq.com,Thank you!

**Comment by static124** [comment]
please send me the sql file,my email address is 744898284@qq.com Thank you!

**Comment by ronyuzhang** [comment]
please send me the sql file,my email address is ronyuzhang@foxmail.com Thank you!

**Comment by lbelis** [comment]
Hi, Can you send me the sql file and your QQ num , i am working on LBS server program , i think we can have some communication about it. My email is 619258055@qq.com, Thank you!

**Comment by TripleZs113** [comment]
Please could you send the sql file to zhzhzh113@outlook.com? many thanks.

**Comment by HelloNick666** [comment]
please send me a sql file , thanks.   1755963909@qq.com
