### ISSUE TITLE
为什么坐标不是x,y,z ？

### ISSUE THREAD

**Issue by ronyuzhang** [megagao/IndoorPos#2]
只有x,y 不能对于实际上的空间吧？很多ibeacon基站都是安装在顶部的。

**Comment by megagao** [comment]
@ronyuzhang 这个做的是二维的定位，只能得出平面坐标。ibeacon安装在顶部的话，可以测量一下ibeacon到定位手机的大致高度，根据ibeacon到手机的距离和两者的高度差，可以算出两者的平面距离。
