### ISSUE TITLE
无法测试

### ISSUE THREAD

**Issue by zhongshuiyuan** [megagao/IndoorPos#4]
大神你好，求份sql文件，感谢之 ：gis_zhong@sina.com

**Comment by megagao** [comment]
已发

**Comment by zhongshuiyuan** [comment]
已收到文件，非常感谢
----- 原始邮件 -----
发件人：MegaGao <notifications@github.com>
收件人：megagao/IndoorPos <IndoorPos@noreply.github.com>
抄送人：zhongshuiyuan <gis_zhong@sina.com>,  Author <author@noreply.github.com>
主题：Re:_[megagao/IndoorPos]_无法测试_(#4)
日期：2017年08月02日 15点55分

已发

&mdash;

**Comment by RockyQu** [comment]
@zhongshuiyuan 兄弟能否发我一份，250533855@qq.com 谢谢了

**Comment by yuezyy** [comment]
大神你好，求ibeacon有关源码，谢谢😊。2359504691@qq.com
