### ISSUE TITLE
在干净的电磁环境中，Path Loss路径损耗指数有没有一个参考值？

### ISSUE THREAD

**Issue by miscab** [megagao/IndoorPos#6]
谢谢！

**Comment by megagao** [comment]
@miscab 这个值不好确定，我们当时的实验环境大概是2.3-3.0之间，建议还是实地测一下，因为受环境影响较大

**Comment by miscab** [comment]
@megagao 谢谢！这需要开发一个测试的APP，然后在实际的环境测试时形成经验值，后续就简单了。
